ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER medirecords_8292 IDENTIFIED BY password;

GRANT CREATE SESSION TO medirecords_8292;

GRANT CREATE TABLE TO medirecords_8292;

ALTER USER medirecords_8292 QUOTA UNLIMITED ON USERS;

